/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2a0043",
        "inverse-surface": "#000d26",
        "on-primary-fixed-variant": "#002e52",
        tertiary: "#7c40a1",
        outline: "#64779d",
        "inverse-primary": "#0097fc",
        "on-primary": "#edf3ff",
        "primary-fixed-dim": "#0097fc",
        "surface-container": "#e0e8ff",
        "secondary-fixed-dim": "#a7c4ff",
        "on-secondary": "#eff2ff",
        "on-tertiary-fixed-variant": "#57187c",
        "surface-tint": "#005ea0",
        "tertiary-fixed-dim": "#ca89f0",
        "surface-container-highest": "#ceddff",
        "primary-fixed": "#47a5ff",
        "surface-container-low": "#ecf0ff",
        "surface-container-high": "#d7e2ff",
        "secondary-fixed": "#bdd2ff",
        "error-container": "#fb5151",
        "surface-bright": "#f5f6ff",
        "primary-container": "#47a5ff",
        "on-primary-fixed": "#000000",
        "on-surface-variant": "#495c80",
        "on-tertiary-container": "#4d0972",
        "surface-dim": "#c1d5ff",
        "inverse-on-surface": "#8a9dc5",
        "on-secondary-fixed": "#00336d",
        "outline-variant": "#9aadd6",
        "on-tertiary": "#fdeeff",
        "on-surface": "#1a2e50",
        "on-secondary-fixed-variant": "#004ea2",
        "on-primary-container": "#002442",
        "on-error": "#ffefee",
        "on-error-container": "#570008",
        "secondary-container": "#bdd2ff",
        "tertiary-container": "#d896fe",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d896fe",
        secondary: "#0659b5",
        error: "#b31b25",
        "on-background": "#1a2e50",
        "surface-variant": "#ceddff",
        background: "#f5f6ff",
        primary: "#005ea0",
        surface: "#f5f6ff",
        "on-secondary-container": "#004591",
        "tertiary-dim": "#6f3394",
        "secondary-dim": "#004da1",
        "error-dim": "#9f0519",
        "primary-dim": "#00528c"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        public: ["Public Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
